// Generated by CoffeeScript 1.8.0
(function() {
  var Logger, backbone;

  backbone = require('backbone4000');

  Logger = require('logger2');

  exports.plugin = backbone.Model.extend4000({
    init: function(callback) {
      var logger;
      logger = new Logger.Logger();
      logger.outputs.push(new Logger.Console());
      this.env.log = logger.log.bind(logger);
      return callback();
    }
  });

}).call(this);
