// Generated by CoffeeScript 1.8.0
(function() {
  var Logger, backbone, _;

  backbone = require('backbone4000');

  Logger = require('logger2');

  _ = require('underscore');

  exports.lego = backbone.Model.extend4000({
    init: function(callback) {
      var logger;
      console.log('initializing logger...');
      logger = this.logger = new Logger.Logger();
      if (!this.settings.outputs) {
        logger.outputs.push(new Logger.Console());
      } else {
        _.map(this.settings.outputs, function(value, name) {
          logger.outputs.push(new Logger[name](value));
          return console.log(name, 'output', value);
        });
      }
      this.env.log = logger.log.bind(logger);
      return callback();
    }
  });

}).call(this);
